source 'https://github.com/CocoaPods/Specs.git'

platform :ios,"10.0"

use_frameworks!

target "WYnews" do


pod 'Alamofire'

pod 'Kingfisher'

pod 'HandyJSON', '~> 4.0.0-beta.1'

pod 'SnapKit'


end
